FP16 STFT updates
adobe-research/convmelspec pull request #3
Opened 2023-04-06 22:35 UTC by nikalra

- Added debug checks to help validate FP16 overflow and underflow errors
- Added clamping to ensure that values through the STFT layer (at mel conversion, power to db) stay within the representable range of the given data type (defaults to FP16, since most models will run in FP16).

2023-04-10 15:12 UTC, njb commented
@nikalra Awesome, will review asap. While you wait, can you sign the Adobe CLA for open source contribution?

2023-04-17 17:00 UTC, njb requested changes
See other comments.

2023-06-12 22:59 UTC, nikalra commented on convmelspec/stft.py
> +        dtype: torch.dtype = torch.float16,
It doesn't look like Torch has CPU implementations for FP16 so that ends up breaking a lot of the tests

2023-06-26 20:26 UTC, njb approved these changes

2023-06-26 20:26 UTC, njb commented on convmelspec/stft.py
> +                def normalized_window_fn(*args, **kwargs):
@nikalra Why is this window norm function only for float16?

2023-06-26 20:26 UTC, merged